on:
  workflow_dispatch:

jobs:
  actions-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: .github/actions/Greeting@v1
        with:
          name: Ahmed
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

  hybird_job:
    runs-on: ubuntu-latest
    steps:
      - name: Run a command in ubuntu VM
        run: echo "This runs on the ubuntu VM"

      - name: Run inside an Alpine container
        usese: docker://alpine:3.14 # the image must be accessible without authentication
        with:
          entrypoint: /bin/sh
          args:
            - -c
            - |
              echo "This is runs inside an Apline container"
      - name: Run another command in ubuntu VM
        run: echo "Back to the VM"

    # if repository is private 
  dockerized_job:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/my-org/my-private-image:latest
      credentials:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
    container: node:20
    steps:
      - run: node --version
      - run: echo "This whole job runs inside a Nodejs container"
