name : First Workflow

on:
 push:
   branches:
     - main
jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
      - name : Print a welcomemessage
        run : echo "Welcom to our first github action workflow"

      - name: Chekcout repository
        uses: actions/checkout@v5.0.0
      - name: List repository files
        run: ls -la
