on: 
# means manual workflow
  workflow_dispatch:
    inputs:
      environment:  
        description: "Choose environment"
        required: true
        default: "staging"
        type: choice
        options:
          - staging
          - production
        
jobs: 
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Dploy application
        run: echo "Deploying the application... "
